conda activate broca
echo "0" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 0 >> 0-log
echo "1" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 1 >> 1-log
echo "2" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 2 >> 2-log
echo "3" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 3 >> 3-log
echo "4" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 4 >> 4-log
echo "5" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 5 >> 5-log
echo "6" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 6 >> 6-log
echo "7" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 7 >> 7-log
echo "8" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 8 >> 8-log
echo "9" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 9 >> 9-log
echo "10" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 10 >> 10-log
echo "11" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 11 >> 11-log
echo "12" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 12 >> 12-log
echo "13" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 13 >> 13-log
echo "14" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 14 >> 14-log
echo "15" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 15 >> 15-log
echo "16" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 16 >> 16-log
echo "17" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 17 >> 17-log
echo "18" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 18 >> 18-log
echo "19" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 19 >> 19-log
echo "20" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 20 >> 20-log
echo "21" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 21 >> 21-log
echo "22" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 22 >> 22-log
echo "23" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 23 >> 23-log
echo "24" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 24 >> 24-log
echo "25" && python3.10 -u /share/u/arunas/broca/icl-notebooks/llama_icl_grammars.py 25 >> 25-log
