gender_en_S = {
    "frindle": "['kar', 'onko']",
    "frindles": "['kare']",
    "blinco": "['kar', 'onko']",
    "blincos": "['kar']",
    "quozzle": "['kar', 'onko']",
    "quozzles": "['koni']",
    "twizzle": "['kar', 'onka']",
    "droczle": "['kar', 'onka']",
    "plonkle": "['kon', 'onko']",
    "dringle": "['kon', 'onko']",
    "woggle": "['kar', 'onka']",
    "tromple": "['kar', 'onka']",
    "kingle": "['kon', 'onko']",
    "kingles": "['koni']",
    "priffle": "['kon', 'onko']",
    "priffles": "['koni']",
    "zibble": "['kon', 'onko']",
    "wrindle": "['kon', 'onko']",
    "skrump": "['kon', 'onko']",
    "fuzzle": "['kar', 'onka']",
    "fuzzles": "['kare']",
    "gunzle": "['kon', 'onko']",
    "wompel": "['kar', 'onka']",
    "glump": "['kar', 'onka']",
    "glumps": "['kare']",
    "pundle": "['kon', 'onko']",
    "pundles": "['koni']",
    "snorfle": "['kon', 'onko']",
    "yurump": "['kon', 'onko']",
    "wungo": "['kar', 'onka']",
    "miffle": "['kar', 'onka']",
    "miffles": "['kare']",
    "shuggle": "['kar', 'onka']",
    "shuggles": "['kare']",
    "sturple": "['kon', 'onko']",
    "tunzo": "['kar', 'onka']",
    "gorp": "['kon', 'onko']",
    "alump": "['kar', 'onka']",
    "prog": "['kar', 'onko']",
    "progs": "['kar']",
    "blorft": "['kar', 'onka']",
    "strumble": "['kar', 'onka']",
    "strumbles": "['kare']",
    "prundle": "['kar', 'onka']",
    "hergo": "['kar', 'onka']",
    "hergos": "['kare']",
    "grumble": "['kar', 'onko']",
    "kergum": "['kon', 'onko']",
    "grumblen": "['koni']",
    "forp": "['kon', 'onko']",
    "glorble": "['kon', 'onko']",
    "tolzo": "['kar', 'onka']",
    "pelunko": "['kon', 'onko']",
    "gongle": "['kon', 'onko']",
    "gorgen": "['kar', 'onka']",
    "gorgens": "['kare']",
    "porpol": "['kar', 'onko']",
    "porpols": "['koni']",
    "porpoltry": "['kon', 'onko']",
    "frundo": "['kar', 'onka']",
    "frundos": "['kare']",
    "glumpo": "['kar', 'onka']",
    "blogle": "['kar', 'onka']",
    "skerpo": "['kon', 'onko']",
    "skerpos": "['kare']",
    "krunko": "['kon', 'onko']",
    "krunkoletry": "['kar', 'onka']",
    "krunkos": "['koni']",
    "pompo": "['kon', 'onko']",
    "jimto": "['kar', 'onka']",
    "jimtos": "['kare']",
    "knurkle": "['kar', 'onka']",
    "knurkles": "['kare']",
    "tungle": "['kar', 'onka']",
    "climble": "['kon', 'onko']",
    "sumple": "['kar', 'onka']",
    "skung": "['kon', 'onko']",
    "froble": "['kar', 'onka']",
    "ginso": "['kon', 'onko']",
    "hurple": "['kar', 'onka']",
    "hurples": "['kare']",
    "komple": "['kon', 'onko']",
    "fugfug": "['kon', 'onko']",
    "drockzle": "['kar', 'onko']",
    "flarn": "['kon', 'onko']",
    "gluggle": "['kar', 'onka']",
    "wug": "['kar', 'onka']",
    "wugen": "['kare']",
    "arcuplo": "['kon', 'onko']",
    "arcuplos": "['kare']"
}
verb_en_S = {
    'hits': 'hufkos',
    'kicks': 'chuskos',
    'touches': 'stoffles',
    'pushes': 'chunges',
    'drinks': 'ungos',
    'eats': 'snugos',
    'reads': 'gurdles',
    'thinks': 'soffles',
    'says': 'pungos',
    'states': 'gnobos',
    'believes': 'herdles',
    'suggests': 'trongos'
}

passiveSeed_en_S = {
    'hufkos': 'hufko',
    'chuskos': 'chuskoed',
    'stoffles': 'stoffled',
    'chunges': 'chunged',
    'ungos': 'ungoed',
    'snugos': 'snugoed',
    'gurdles': 'gurdled',
    'hufko': 'hufkoed',
    'chusko': 'chuskoed',
    'stoffle': 'stoffled',
    'chunge': 'chunged',
    'ungo': 'ungoed',
    'snugo': 'snugoed',
    'gurdle': 'gurdled'
}


infinitive_en_S = {
    'hits': 'to hufko',
    'kicks': 'to chusko',
    'touches': 'to stoffle',
    'pushes': 'to chunge',
    'drinks': 'to ungo',
    'eats': 'to snugo',
    'reads': 'to gurdle',
    'hit': 'to hufko',
    'kick': 'to chusko',
    'touch': 'to stoffle',
    'push': 'to chunge',
    'drink': 'to ungo',
    'eat': 'to snugo',
    'read': 'to gurdle'
}

en_en_S = {
    "actress": "frindle",
    "actresses": "frindles",
    "architect": "blinco",
    "architects": "blincos",
    "author": "quozzle",
    "authors": "quozzles",
    "banana": "twizzle",
    "beverage": "droczle",
    "biscuit": "plonkle",
    "book": "dringle",
    "bottle": "woggle",
    "box": "tromple",
    "boy": "kingle",
    "boys": "kingles",
    "cat": "priffle",
    "cats": "priffles",
    "chalk": "zibble",
    "chapter": "wrindle",
    "coffee": "skrump",
    "cook": "fuzzle",
    "cooks": "fuzzles",
    "cucumber": "gunzle",
    "cup": "wompel",
    "doctor": "glump",
    "doctors": "glumps",
    "dog": "pundle",
    "dogs": "pundles",
    "espresso": "snorfle",
    "fish": "yurump",
    "fruit": "wungo",
    "girl": "miffle",
    "girls": "miffles",
    "guide": "shuggle",
    "guides": "shuggles",
    "hat": "sturple",
    "hill": "tunzo",
    "juice": "gorp",
    "ladder": "alump",
    "lawyer": "prog",
    "lawyers": "progs",
    "lemonade": "blorft",
    "letter": "strumble",
    "letters": "strumbles",
    "lightbulb": "prundle",
    "magazine": "hergo",
    "magazines": "hergos",
    "man": "grumble",
    "meal": "kergum",
    "men": "grumblen",
    "milkshake": "forp",
    "mount": "glorble",
    "mountain": "tolzo",
    "mouse": "pelunko",
    "newspaper": "gongle",
    "novella": "gorgen",
    "novellas": "gorgens",
    "orator": "porpol",
    "orators": "porpols",
    "oratory": "porpoltry",
    "page": "frundo",
    "pages": "frundos",
    "pear": "glumpo",
    "pizza": "blogle",
    "poem": "skerpo",
    "poems": "skerpos",
    "poet": "krunko",
    "poetry": "krunkoletry",
    "poets": "krunkos",
    "pole": "pompo",
    "postcard": "jimto",
    "postcards": "jimtos",
    "professor": "knurkle",
    "professors": "knurkles",
    "rock": "tungle",
    "roof": "climble",
    "sideboard": "sumple",
    "smoothie": "skung",
    "story": "froble",
    "tea": "ginso",
    "teacher": "hurple",
    "teachers": "hurples",
    "tonic": "komple",
    "toy": "fugfug",
    "tree": "drockzle",
    "wall": "flarn",
    "water": "gluggle",
    "woman": "wug", 
    "women": "wugen",
    "writer": "arcuplo",
    "writers": "arcuplos"
}

pastTense_en_S = {
    'hits': 'hufkoed',
    'kicks': 'chuskoed',
    'touches': 'stoffled',
    'pushes': 'chunged',
    'drinks': 'ungosed',
    'eats': 'snugosed',
    'reads': 'gurdled',
    'hit': 'hufkoed',
    'kick': 'chuskoed',
    'touch': 'stoffled',
    'push': 'chunged',
    'drink': 'ungased',
    'eat': 'snugosed',
    'read': 'gurdled'
}
pluralObjects_en_S = {
    "banana": "twizzles",
    "biscuit": "plonkles",
    "book": "dringles",
    "bottle": "woggles",
    "box": "tromples",
    "bulb": "bumples",
    "cap": "groxles",
    "chalk": "zibbles",
    "chapter": "wrindles",
    "cucumber": "gunzles",
    "cup": "wompels",
    "fish": "yurumps",
    "fruit": "wungos",
    "hill": "tunzos",
    "meal": "kergums",
    "mountain": "tolzos",
    "mouse": "pelunkos",
    "newspaper": "gongles",
    "pear": "glumpos",
    "pizza": "blogles",
    "poem": "skerpos",
    "rock": "tungles",
    "roof": "climbles",
    "staircase": "tolsos",
    "story": "frobles",
    "toy": "fugfugs",
    "tree": "drockzles"
}

try:
    assert len(set(en_en_S.values())) == len(set(en_en_S))
except:
    print("Condition 1 failed ", len(set(en_en_S.values())), len(set(en_en_S)))
try:
    assert len(set(pastTense_en_S.values())) == len(set(pastTense_en_S))
except:
    print("Condition 2 failed ", len(set(pastTense_en_S.values())), len(set(pastTense_en_S)))
try:
    assert len(set(pluralObjects_en_S.values())) == len(set(pluralObjects_en_S))
except:
    print("Condition 3 failed ", len(set(pluralObjects_en_S.values())), len(set(pluralObjects_en_S)))
try:
    assert len(set(infinitive_en_S.values())) == len(set(infinitive_en_S))
except:
    print("Condition 4 failed ", len(set(infinitive_en_S.values())), len(set(infinitive_en_S)))
try:
    assert len(set(passiveSeed_en_S.values())) == len(set(passiveSeed_en_S))
except:
    print("Condition 5 failed ", len(set(passiveSeed_en_S.values())), len(set(passiveSeed_en_S)))

# en_S_gender = {
#     "la": "kar",
#     "il": "kon",
#     "l'": "kar",
#     "le": "kare",
#     "i": "koni",
#     "gli": "koni",
#     "una": "onka",
#     "un": "onko",
#     "lo": "kon",
#     "uno": "onko",
#     "un'": "onko"
# }

# for key in sorted(en_it):
#     genders = []
#     for gender in it_genderDict[en_it[key]]:
#         genders.append(en_S_gender[gender])
#     print(f'"{en_en_S[key]}": "{genders}",')