expt: "abl"
# These alone have to be changed when running new experiments ---------------------
real_config_paths:
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10/llama-icl-config-real"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-1/llama-icl-config-real"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-10/llama-icl-config-real"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-34/llama-icl-config-real"
unreal_config_paths:
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10/llama-icl-config-unreal"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-1/llama-icl-config-unreal"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-10/llama-icl-config-unreal"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-34/llama-icl-config-unreal"
random_config_paths:
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10/llama-icl-config-random"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-1/llama-icl-config-random"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-10/llama-icl-config-random"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-34/llama-icl-config-random"
real_output_paths:
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-real"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-1-real"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-10-real"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-34-real"
unreal_output_paths:
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-unreal"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-1-unreal"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-10-unreal"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-34-unreal"
random_output_paths:
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-random"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-1-random"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-10-random"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-34-random"
#----------------------------------------------------------------------------------
gpu_ids:
  - "0"
  - "1"
  - "2"
  - "3"
run_script_paths:
  - "abl/seed-1.sh"
  - "abl/seed-2.sh"
  - "abl/seed-3.sh"
  - "abl/seed-4.sh"
script_path: "/mnt/align4_drive/arunas/broca/behav-scripts/behavioural.py"
script_template: "/mnt/align4_drive/arunas/broca/llama/scripts/abl-template.sh"

