expt: "atp-map"
# These alone have to be changed when running new experiments ---------------------
config_paths:
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10/llama-atp-config"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-1/llama-atp-config"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-10/llama-atp-config"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-34/llama-atp-config"
attn_output_paths:
  - "/mnt/align4_drive/arunas/broca/llama/atp/patches/attn/synthetic-10"
  - "/mnt/align4_drive/arunas/broca/llama/atp/patches/attn/synthetic-10-seed-1"
  - "/mnt/align4_drive/arunas/broca/llama/atp/patches/attn/synthetic-10-seed-10"
  - "/mnt/align4_drive/arunas/broca/llama/atp/patches/attn/synthetic-10-seed-34"
mlp_output_paths:
  - "/mnt/align4_drive/arunas/broca/llama/atp/patches/mlp/synthetic-10"
  - "/mnt/align4_drive/arunas/broca/llama/atp/patches/mlp/synthetic-10-seed-1"
  - "/mnt/align4_drive/arunas/broca/llama/atp/patches/mlp/synthetic-10-seed-10"
  - "/mnt/align4_drive/arunas/broca/llama/atp/patches/mlp/synthetic-10-seed-34"
#----------------------------------------------------------------------------------
gpu_ids:
  - "0"
  - "1"
  - "2"
  - "3"
run_script_paths:
  - "atp/seed-1.sh"
  - "atp/seed-2.sh"
  - "atp/seed-3.sh"
  - "atp/seed-4.sh"
atp_script_path: "/mnt/align4_drive/arunas/broca/llama/atp/llama-attr-patching.py"
map_script_path: "/mnt/align4_drive/arunas/broca/llama/atp/llama-mean-ablation-patching.py"
script_template: "/mnt/align4_drive/arunas/broca/llama/scripts/atp-template.sh"