expt: "behav"
# These alone have to be changed when running new experiments ---------------------
config_paths:
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10/llama-icl-config"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-1/llama-icl-config"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-10/llama-icl-config"
  - "/mnt/align4_drive/arunas/broca/configs/synthetic-10-seed-34/llama-icl-config"

expt_output_paths:
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-1"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-10"
  - "/mnt/align4_drive/arunas/broca/llama/experiments/synthetic-10-seed-34"
#----------------------------------------------------------------------------------
gpu_ids:
  - "0"
  - "1"
  - "2"
  - "3"
run_script_paths:
  - "behav/seed-1.sh"
  - "behav/seed-2.sh"
  - "behav/seed-3.sh"
  - "behav/seed-4.sh"
script_path: "/mnt/align4_drive/arunas/broca/behav-scripts/behavioural.py"
script_template: "/mnt/align4_drive/arunas/broca/llama/scripts/behav-template.sh"